### ISSUE TITLE
kinect v2 real-time support

### ISSUE THREAD

**Issue by ghost** [TinyTinni/KinectFaker#1]
It would be nice if the Kinect v2 could interpreted as a Kinect v1 sensor for applications like garry's mod.

**Comment by TinyTinni** [comment]
Sorry but I don't own the Kinect v2 and i guess it will be hard without any tests with the hardware

**Comment by ghost** [comment]
I'm able to test with the hardware.

**Comment by TinyTinni** [comment]
But still need to write functions with SDK v2 which substitute all the functions in SDK v1 which are used by Garry's Mod which are (for me) unknown.

Sounds like some work which can only be tested with a big delay.

If you have all the Kinect v1 functions which are used by Garry's Mod, we can discuss it how much work it would be, simulating these functions with the v2 SDK.
