### ISSUE TITLE
Why does Kinect need to be connected?

### ISSUE THREAD

**Issue by SebastianBoyd** [TinyTinni/KinectFaker#2]
I know this is a super old project but I’m starting work on something similar. Can you tell me what limitations you ran into that required the real Kinect to be plugged in?

**Comment by TinyTinni** [comment]
When I remember correctly, the Kinect needed to be connected for the delivered Kinect Studio, the debug Program delivered by the Microsoft SDK (v1.8).
With the Kinect Studio, you could record skeleton animations and replay it, but it didn't work (or I couldn't find any option) when the Kinect device was not plugged in your current PC even when the animation came from a file.

This project helped to have a skeleton animation from a file while the Kinect device didn't need to be connected. When using this program, the kinect doesn't need to be plugged in as long as you have a recorded animation.

**Comment by SebastianBoyd** [comment]
Thanks for getting back to me! It’s a big help. I’ll see what I can figure out from there.
